"""face clusters embeddings and photo labels

Revision ID: 3a1fbec7c56c
Revises: 22f550c858ed
Create Date: 2026-05-26 22:17:14.610518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3a1fbec7c56c'
down_revision: Union[str, None] = '22f550c858ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('representative_photo_id', sa.UUID(), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['representative_photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'label', name='uq_photo_labels_photo_id_label')
    )
    op.create_index('ix_photo_labels_label', 'photo_labels', ['label'], unique=False)
    op.create_index('ix_photo_labels_photo_id', 'photo_labels', ['photo_id'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['face_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_face_embeddings_cluster_id', 'face_embeddings', ['cluster_id'], unique=False)
    op.create_index('ix_face_embeddings_photo_id', 'face_embeddings', ['photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_face_embeddings_photo_id', table_name='face_embeddings')
    op.drop_index('ix_face_embeddings_cluster_id', table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index('ix_photo_labels_photo_id', table_name='photo_labels')
    op.drop_index('ix_photo_labels_label', table_name='photo_labels')
    op.drop_table('photo_labels')
    op.drop_table('face_clusters')
    # ### end Alembic commands ###
