"""albums pages items

Revision ID: c262da1734f8
Revises: 3a1fbec7c56c
Create Date: 2026-05-27 16:11:27.009020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c262da1734f8'
down_revision: Union[str, None] = '3a1fbec7c56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('style', sa.Enum('MODERN', 'CLASSIC', 'KIDS', 'ROMANTIC', 'MINIMALIST', name='album_style', native_enum=False, length=32), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('layout_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id', 'index', name='uq_album_pages_album_id_index')
    )
    op.create_index('ix_album_pages_album_id', 'album_pages', ['album_id'], unique=False)
    op.create_table('album_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('comment_position', sa.Enum('ABOVE', 'BELOW', 'START', 'END', 'NONE', name='comment_position', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['album_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_album_items_page_id', 'album_items', ['page_id'], unique=False)
    op.create_index('ix_album_items_photo_id', 'album_items', ['photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_album_items_photo_id', table_name='album_items')
    op.drop_index('ix_album_items_page_id', table_name='album_items')
    op.drop_table('album_items')
    op.drop_index('ix_album_pages_album_id', table_name='album_pages')
    op.drop_table('album_pages')
    op.drop_table('albums')
    # ### end Alembic commands ###
